### PR TITLE
Updated attacks

### PR DESCRIPTION
**Pull request by importhuman**
I've added a few fire type moves, and modified some fire and electric type moves. Please let me know if I should continue like this or should I add attacks based on the old style. I've also added a suggestions.md file, for now the thing I have in mind is to increase starting pokemon level from 0 to 5. This is partly to be consistent with the games, but mainly because the wild pokemon levels are quite high compared to the player's pokemon. I tried changing the starting level directly, but that leads to missing out on learning a new move at level 2.

### CODE REVIEW

**Comment by Sahil-k1509** [comment]
Your virtual environment files also got uploaded along with code. Is it by mistake Or it serves a purpose?

**Comment by Sahil-k1509** [comment]
Yeah we can keep the starting level as 5 and remove the lvl2 attack learning part. Ik viridian forest is hard. XD took me 2hourse to catch good pokemons there and level all of them to 20

**Comment by Sahil-k1509** [comment]
@importhuman  i have invited you to accept the report access. You can merge pull requests without me approving.

**Comment by importhuman** [comment]
venv files must've been uploaded accidentally, I'll try removing them from git. I haven't read the entire code yet, so I can't make the starting level 5 without letting go of the new move at level 2. Also since we don't have secondary move effects as of now, I'll proceed according to your move style, adding moves with various damage, PP, accuracy and recoil. Is it possible to manipulate the saved game for testing purposes? Otherwise it will be difficult to check all the stages of the game as and when required.

**Comment by Sahil-k1509** [comment]
yeah. we can give an option in save game to input the name of saved file. if its already present it will overwrite. And in load game we can display all the pkl extension files present and ask user to choose which game he want to load.

**Comment by importhuman** [comment]
No, I meant can we change saved game data? That way we can test out any new code and features from any point we want, and without having to affect the original save.

**Comment by Sahil-k1509** [comment]
that can be done too. just change the pokemon trainers parameters(gymbadges, money, pokemons, current city etc) and save the game. when u load. those changes will be applied. that way you can warp through game.

**Comment by importhuman** [comment]
Which file do I need to edit for those? Haven't checked out everything, just adding some attacks for now 😅

**Comment by Sahil-k1509** [comment]
in the main.py file. Before the player enters infinite while loop. you can make all the changes in player there(line 144). because the main_game function(defined in city_games.py 1194 line) takes the player and executes code of whichever is current city is(navigation is done using this function only by calling it again and again after changing player.currentlocation). Say you want the player to start from cinnabar island with all 8 badges. You can do player.currentLocation = 'Cinnabar Island'; player.badges = ['boulder badge', 'cascade badge',  .....] in main.py and when it enters infinite loop, they will be applied. (Make sure to comment it out before you rerun program, then uncomment and make new changes to test another situation. You can also define your own pokemons there and assign it to player. For that, define a Pokemon Object initialized with zero level and use npcPokemonReady to upgrade to any level. Directly initializing this any level will cause the pokemon to not learn previous attacks or evolve)

**Comment by importhuman** [comment]
I'll try this all out soon, today I'll try to update attacks of all types, and add a separate branch for other types not coded for yet.

**Pull request merged**
